server:
  port: 6000

spring:
  application:
    name: gulimall-coupon
  datasource:
    username: root
    password: mysql80password
    url: jdbc:mysql://49.234.42.199:3306/guli?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 49.234.42.199:8848

    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: 49.234.42.199:8858

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  #\u8BBE\u7F6E\u5B9E\u4F53\u7C7B\u7684\u81EA\u589E\u4E3B\u952E
  global-config:
    db-config:
      id-type: auto

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

